#!/usr/bin/env bash

# light
# Control the brightness of my laptop
# By: Jhonfs

id=$(xrandr -q | grep ' connected' | head -n 1 | cut -d ' ' -f1)
gb=$(xrandr --verbose | grep 'Brightness' | cut -d ' ' -f2 | cut -d '0' -f2 | cut -d '.' -f2)
e=$(xrandr --verbose | grep 'Brightness' | cut -d ' ' -f2)

case $gb in
    9) v=0.8;;
    8) v=0.7;;
    7) v=0.6;;
    6) v=0.5;;
    5) v=0.4;;
    4) v=0.3;;
    3) v=0.2;;
    2) v=0.1;;
    1) v=0.0;;
    0) v=$e;;
    *) v=0.9;;
esac

xrandr --output $id --brightness $v
